server.port=8080

# Neon PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://ep-quiet-leaf-a1xr1nuj-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UrR43LvHsaPu

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
